# Generated by Django 4.2.1 on 2023-06-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmoviemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieApp.category'),
        ),
    ]
